#!/bin/env bash

echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"

# For TCP sockets
ss -tlnp | awk 'NR>1 {print "tcp", $2, $3, $4, $5, $1, $6}'

# For UDP sockets
ss -ulnp | awk 'NR>1 {print "udp", $2, $3, $4, $5, $1, $6}'

echo "Active UNIX domain sockets (only servers)"
echo "Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path"

# For Unix sockets
ss -xlnp | awk 'NR>1 {print "unix", $2, $3, $4, $5, $1, $6, $7}'
